# Generated by Django 5.0.1 on 2024-01-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daily_log',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Script_Name', models.CharField(max_length=256)),
                ('Client_Name', models.CharField(max_length=256)),
                ('Client_Code', models.CharField(max_length=8)),
                ('Buy_Date', models.DateField()),
                ('Buy_Rate', models.FloatField()),
                ('Buy_Quantity', models.IntegerField()),
                ('Buy_Amount', models.FloatField(default='', editable=False)),
                ('Sell_Date', models.DateField(blank=True, default='', null=True)),
                ('Sell_Rate', models.FloatField(blank=True, default='0', null=True)),
                ('Sell_Quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('Sell_Amount', models.FloatField(blank=True, default='0', editable=False, null=True)),
                ('Net_Quantity', models.IntegerField(default='', editable=False)),
                ('Net_Pl', models.FloatField(default=0.0, editable=False)),
            ],
            options={
                'ordering': ['Id'],
            },
        ),
    ]
