# Generated by Django 2.1.5 on 2024-01-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daily_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Script_name', models.CharField(max_length=256)),
                ('Client_name', models.CharField(max_length=256)),
                ('Client_code', models.CharField(max_length=8)),
                ('Buy_date', models.DateField()),
                ('Buy_rate', models.FloatField()),
                ('Buy_quantity', models.IntegerField()),
                ('Buy_amount', models.FloatField(default='', editable=False)),
                ('Sell_date', models.DateField()),
                ('Sell_rate', models.FloatField()),
                ('Sell_quantity', models.IntegerField()),
                ('Sell_amount', models.FloatField(default='', editable=False)),
                ('Net_pl', models.FloatField(default=0.0, editable=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
