# Generated by Django 2.1.5 on 2024-01-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_log',
            name='Net_quantity',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
