# Generated by Django 5.0.1 on 2024-01-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_log',
            name='Cmp_Rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
