# Generated by Django 5.0.1 on 2024-01-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_log',
            name='Net_Avg',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
