# Generated by Django 2.1.5 on 2024-01-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_daily_log_net_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_log',
            name='Net_quantity',
            field=models.IntegerField(default='', editable=False),
        ),
    ]
