# Generated by Django 5.0.1 on 2024-01-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_daily_log_net_amount_alter_daily_log_net_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_log',
            name='Cmp_Rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='Net_Avg',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
