# Generated by Django 5.0.1 on 2024-01-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20240104_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily_log',
            options={'ordering': ['Id']},
        ),
        migrations.RenameField(
            model_name='daily_log',
            old_name='Buy_amount',
            new_name='Buy_Amount',
        ),
        migrations.RenameField(
            model_name='daily_log',
            old_name='Buy_date',
            new_name='Buy_Date',
        ),
        migrations.RenameField(
            model_name='daily_log',
            old_name='Buy_quantity',
            new_name='Buy_Quantity',
        ),
        migrations.RenameField(
            model_name='daily_log',
            old_name='Buy_rate',
            new_name='Buy_Rate',
        ),
        migrations.RenameField(
            model_name='daily_log',
            old_name='Client_code',
            new_name='Client_Code',
        ),
        migrations.RenameField(
            model_name='daily_log',
            old_name='Client_name',
            new_name='Client_Name',
        ),
        migrations.RenameField(
            model_name='daily_log',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='daily_log',
            old_name='Net_pl',
            new_name='Net_Pl',
        ),
        migrations.RenameField(
            model_name='daily_log',
            old_name='Net_quantity',
            new_name='Net_Quantity',
        ),
        migrations.RenameField(
            model_name='daily_log',
            old_name='Script_name',
            new_name='Script_Name',
        ),
        migrations.RenameField(
            model_name='daily_log',
            old_name='Sell_amount',
            new_name='Sell_Amount',
        ),
        migrations.RenameField(
            model_name='daily_log',
            old_name='Sell_date',
            new_name='Sell_Date',
        ),
        migrations.RenameField(
            model_name='daily_log',
            old_name='Sell_quantity',
            new_name='Sell_Quantity',
        ),
        migrations.RenameField(
            model_name='daily_log',
            old_name='Sell_rate',
            new_name='Sell_Rate',
        ),
    ]
