# Generated by Django 5.0.1 on 2024-01-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_daily_log_cmp_rate_alter_daily_log_net_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_log',
            name='M2M',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
