# Generated by Django 5.0.1 on 2024-01-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_bhavcpy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bhavcpy',
        ),
    ]
