# Generated by Django 5.0.1 on 2024-01-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_daily_log_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_log',
            name='Net_Quantity',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='Sell_Amount',
            field=models.FloatField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='Sell_Quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='Sell_Rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
