# Generated by Django 5.0.1 on 2024-01-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_delete_bhavcpy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_log',
            name='Sell_Amount',
            field=models.FloatField(default='', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='Sell_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='Sell_Quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='Sell_Rate',
            field=models.FloatField(null=True),
        ),
    ]
