# Generated by Django 5.0.1 on 2024-01-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_daily_log_sell_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_log',
            name='Sell_Amount',
            field=models.FloatField(blank=True, default='0', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='Sell_Date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='Sell_Quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='daily_log',
            name='Sell_Rate',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
